version: "3.8"
name: todo-app

services:
  nginx:
    image: nginx:1.17
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
    restart: always

  frontend:
    image: "node:22"
    container_name: frontend
    build: ./frontend
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend/:/home/node/app
      - /home/node/app/node_modules
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm start"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: todo-app/backend
    container_name: backend
    build: ./backend
    working_dir: /usr/src/app
    volumes:
      - ./backend/:/usr/src/app
    expose:
      - "3001"
    ports:
      - "8001:3001"
    command: "python src/server.py"
    environment:
      - DEBUG=true
    env_file:
      - .env
    restart: unless-stopped
