name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Scan Backend Code with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs' 
          input: './backend' 
          format: 'table'
          exit-code: '0' 
          severity: 'CRITICAL,HIGH' 
          

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/todo-backend:cache
          cache-to: type=inline,mode=max

      - name: Scan Backend Image with Trivy (pre-push)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/todo-backend:latest'
          format: 'table'
          exit-code: '0' 
          severity: 'CRITICAL,HIGH' 

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest

          
      - name: Scan Frontend Code with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs' 
          input: './frontend' 
          format: 'table'
          exit-code: '0' 
          severity: 'CRITICAL,HIGH' 
         

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/todo-frontend:cache
          cache-to: type=inline,mode=max


      - name: Scan Frontend Image with Trivy (pre-push)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest'
          format: 'table'
          exit-code: '0' 
          severity: 'CRITICAL,HIGH' 

      
      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest


    
      

