GitHub Actions Workflow: Build and Push Docker Images 
This version of the workflow removes the explicit testing steps.

name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Reverted timeout as testing steps are removed

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- Build and Push Backend Image ---
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/todo-backend:cache
          cache-to: type=inline

      # --- Scan Backend Image for Vulnerabilities ---
      - name: Scan Backend Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/todo-backend:latest'
          format: 'table'
          exit-code: '1' 
          severity: 'CRITICAL,HIGH' 

      # --- Build and Push Frontend Image ---
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/todo-frontend:cache
          cache-to: type=inline

      # --- Scan Frontend Image for Vulnerabilities ---
      - name: Scan Frontend Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest'
          format: 'table'
          exit-code: '1' 
          severity: 'CRITICAL,HIGH' 
